### ISSUE TITLE
Feature Request - Add support for Cloudvision as a Service

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#233]
## Request Type

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (please describe):

## Detailed Description

Implement CV as a Service authentication support

**Is your feature request related to a problem? Please describe.**

CVaaS authenticates the user using a token which is different from the on-premise instance of Cloudvision. The authentication mechanism should be changed to support both options.

## Todo:

- [x] Create authentication method in `module_utils`
- [ ] Add trigger to select either on-prem or cvaas
- [ ] Update `cv_facts`
- [ ] Update `cv_configlet`
- [ ] Update `cv_container`
- [ ] Update `cv_device`
- [ ] Update `cv_task`
- [ ] Create HOW-TO documentation
- [ ] Run testing against CVaaS instance
- [ ] Validate AVD workflow

**Comment by titom73** [comment]
cvprac implementation for cvaas:

```python
>>> from cvprac.cvp_client import CvpClient
>>> clnt = CvpClient()
>>> clnt.connect(nodes=['cvaas'], username='', 
				 password='', 
				 is_cvaas=True, 
				 cvaas_token='user token')
>>> result = clnt.api.get_cvp_info()
>>> print result
{u'version': u'cvaas'}
>>>
```
