### ISSUE TITLE
EPIC: Molecule tests

### ISSUE THREAD

**Issue by sugetha24** [aristanetworks/ansible-cvp#642]
# EPIC - Molecule tests

## Project Goals

End to end integration tests

## Task List
 
- [x] aristanetworks/ansible-cvp#621
- [x] aristanetworks/ansible-cvp#624
- [x] aristanetworks/ansible-cvp#625
- [x] aristanetworks/ansible-cvp#627
- [x] aristanetworks/ansible-cvp#630
- [x] aristanetworks/ansible-cvp#631
- [x] aristanetworks/ansible-cvp#634
- [x] aristanetworks/ansible-cvp#635
- [x] aristanetworks/ansible-cvp#659
