### ISSUE TITLE
EPIC: CI pipeline

### ISSUE THREAD

**Issue by sugetha24** [aristanetworks/ansible-cvp#649]
# EPIC - CI pipeline

## Project Goals

Improvements to CI pipeline 

## Task List
 
- [x] aristanetworks/ansible-cvp#648
- [x] aristanetworks/ansible-cvp#653
- [x] aristanetworks/ansible-cvp#645
- [ ] aristanetworks/ansible-cvp#617
- [x] aristanetworks/ansible-cvp#656
